[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
wu_pay_solana = "Do7Ta4RFCwrBhbESGcMg6W7sLNqXMcq5E7YV5CAEZhij"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lebingxie/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

